version: "3"
services:
  php:
    build: ./test_app
    container_name: ${PREFIX_NAME}_php
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./test_app:/app
  database:
    build:
      context: ./database
    volumes:
    - database:/var/lib/mysql
    ports:
    - "${MYSQL_PORT}:3306"
    env_file:
    - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0

volumes:
  database: