version: '3.7'

services:
  web:
    build: ./web
    ports:
      - "${HTTP_PORT}:80"
    volumes: 
      - ./web/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - wp-data:/var/www/html
    depends_on: 
      - wp

  wp:
    build: ./wordpress
    env_file: .env
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - wp-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

volumes:
    db_data:
    wp-data: